### ISSUE TITLE
Page does nothing after uploading roster

### ISSUE THREAD

**Issue by Chodey12** [Floppy/scriptorum#9] opened 2019-12-21 23:54 UTC
Nothing happens on the screen after selecting rosz file.

[IG Roster 100.txt](https://github.com/Floppy/scriptorum/files/3991944/IG.Roster.100.txt)

**Comment by Floppy** [comment] 2019-12-22 12:28
Thanks! This is an interesting one, it's because two of the models are lacking a faction keyword, which I thought would always be there. It's handled now, but I wonder if this is an error in the base battlescribe data...

**Comment by Floppy** [comment] 2019-12-22 12:29
Resolved in eac9c9eff00db9eef77e3310364231e6b2a23708

**Closed by Floppy** 2019-12-22 12:29 UTC

**Comment by Floppy** [comment] 2019-12-22 12:39
Yep, confirmed, the faction tags are missing in https://github.com/BSData/wh40k-killteam/blob/master/Astra%20Militarum.cat.

**Comment by Floppy** [comment] 2019-12-22 12:40
Reported as a new bug in https://github.com/BSData/wh40k-killteam/issues/419, and I'll fix it later upstream if I get time.
